package wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Onekey_App_ServiceHttpPost", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OnekeyAppServiceHttpPost {

	/**
	 * 
	 * @param strUserInfo
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_UserInfo")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairUserInfo(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strUserInfo") String strUserInfo);

	/**
	 * 
	 * @param strLoginKey
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepairType")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairType(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strLoginKey") String strLoginKey);

	/**
	 * 
	 * @param strRepairTypeId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_Scene")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairScene(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strRepairTypeId") String strRepairTypeId);

	/**
	 * 
	 * @param strType
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_POOL")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairPOOL(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strType") String strType);

	/**
	 * 
	 * @param strRepairTypeId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_Ne")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairNe(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strRepairTypeId") String strRepairTypeId);

	/**
	 * 
	 * @param strPoolId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_Ne_ByPoolId")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairNeByPoolId(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strPoolId") String strPoolId);

	/**
	 * 
	 * @param strRepairTypeId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_AuditorByRepairTypeId")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairAuditorByRepairTypeId(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strRepairTypeId") String strRepairTypeId);

	/**
	 * 
	 * @param strInstructInfo
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_InstructInfo")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairInstructInfo(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strInstructInfo") String strInstructInfo);

	/**
	 * 
	 * @param strSMSInfo
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_SMSInfo")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairSMSInfo(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strSMSInfo") String strSMSInfo);

	/**
	 * 
	 * @param strID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_SelectInstructionIssued")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairSelectInstructionIssued(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strID") String strID);

	/**
	 * 
	 * @param strID
	 * @return returns byte[]
	 */
	@WebMethod(operationName = "GetOnekyRepair_GetLog")
	@WebResult(name = "base64Binary", targetNamespace = "http://tempuri.org/", partName = "Body")
	public byte[] getOnekyRepairGetLog(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strID") String strID);

	/**
	 * 
	 * @param strID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_GetQueryCmd")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairGetQueryCmd(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strID") String strID);

	/**
	 * 
	 * @param strId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_Ne_ByQueryCmdId")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairNeByQueryCmdId(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strId") String strId);

	/**
	 * 
	 * @param strId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_Ne_ByCity")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairNeByCity(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strId") String strId);

	/**
	 * 
	 * @param strJson
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_Ne_ByData")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairNeByData(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strJson") String strJson);

	/**
	 * 
	 * @param strJson
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_List_ByHCHL")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairListByHCHL(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strJson") String strJson);

	/**
	 * 
	 * @param strInstructionInfo
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_InstructionIssued")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getOnekyRepairInstructionIssued(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strInstructionInfo") String strInstructionInfo);

	/**
	 * 
	 * @param strLoginKey
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ClientRefrash")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String clientRefrash(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strLoginKey") String strLoginKey);

	/**
	 * 
	 * @param strLoginKey
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ClientLogout")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String clientLogout(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strLoginKey") String strLoginKey);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetUpdateInfo")
	@WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
	public String getUpdateInfo();

}
