package wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Onekey_App_ServiceSoap", targetNamespace = "http://tempuri.org/")
public interface OnekeyAppServiceSoap {

	/**
	 * 
	 * @param strUserInfo
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_UserInfo", action = "http://tempuri.org/GetOnekyRepair_UserInfo")
	@WebResult(name = "GetOnekyRepair_UserInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_UserInfo", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairUserInfo")
	@ResponseWrapper(localName = "GetOnekyRepair_UserInfoResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairUserInfoResponse")
	public String getOnekyRepairUserInfo(
			@WebParam(name = "strUserInfo", targetNamespace = "http://tempuri.org/") String strUserInfo);

	/**
	 * 
	 * @param strLoginKey
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepairType", action = "http://tempuri.org/GetOnekyRepairType")
	@WebResult(name = "GetOnekyRepairTypeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepairType", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairType")
	@ResponseWrapper(localName = "GetOnekyRepairTypeResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairTypeResponse")
	public String getOnekyRepairType(
			@WebParam(name = "strLoginKey", targetNamespace = "http://tempuri.org/") String strLoginKey);

	/**
	 * 
	 * @param strRepairTypeId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_Scene", action = "http://tempuri.org/GetOnekyRepair_Scene")
	@WebResult(name = "GetOnekyRepair_SceneResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_Scene", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairScene")
	@ResponseWrapper(localName = "GetOnekyRepair_SceneResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairSceneResponse")
	public String getOnekyRepairScene(
			@WebParam(name = "strRepairTypeId", targetNamespace = "http://tempuri.org/") String strRepairTypeId);

	/**
	 * 
	 * @param strType
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_POOL", action = "http://tempuri.org/GetOnekyRepair_POOL")
	@WebResult(name = "GetOnekyRepair_POOLResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_POOL", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairPOOL")
	@ResponseWrapper(localName = "GetOnekyRepair_POOLResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairPOOLResponse")
	public String getOnekyRepairPOOL(
			@WebParam(name = "strType", targetNamespace = "http://tempuri.org/") String strType);

	/**
	 * 
	 * @param strRepairTypeId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_Ne", action = "http://tempuri.org/GetOnekyRepair_Ne")
	@WebResult(name = "GetOnekyRepair_NeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_Ne", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairNe")
	@ResponseWrapper(localName = "GetOnekyRepair_NeResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairNeResponse")
	public String getOnekyRepairNe(
			@WebParam(name = "strRepairTypeId", targetNamespace = "http://tempuri.org/") String strRepairTypeId);

	/**
	 * 
	 * @param strPoolId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_Ne_ByPoolId", action = "http://tempuri.org/GetOnekyRepair_Ne_ByPoolId")
	@WebResult(name = "GetOnekyRepair_Ne_ByPoolIdResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_Ne_ByPoolId", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairNeByPoolId")
	@ResponseWrapper(localName = "GetOnekyRepair_Ne_ByPoolIdResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairNeByPoolIdResponse")
	public String getOnekyRepairNeByPoolId(
			@WebParam(name = "strPoolId", targetNamespace = "http://tempuri.org/") String strPoolId);

	/**
	 * 
	 * @param strRepairTypeId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_AuditorByRepairTypeId", action = "http://tempuri.org/GetOnekyRepair_AuditorByRepairTypeId")
	@WebResult(name = "GetOnekyRepair_AuditorByRepairTypeIdResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_AuditorByRepairTypeId", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairAuditorByRepairTypeId")
	@ResponseWrapper(localName = "GetOnekyRepair_AuditorByRepairTypeIdResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairAuditorByRepairTypeIdResponse")
	public String getOnekyRepairAuditorByRepairTypeId(
			@WebParam(name = "strRepairTypeId", targetNamespace = "http://tempuri.org/") String strRepairTypeId);

	/**
	 * 
	 * @param strInstructInfo
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_InstructInfo", action = "http://tempuri.org/GetOnekyRepair_InstructInfo")
	@WebResult(name = "GetOnekyRepair_InstructInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_InstructInfo", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairInstructInfo")
	@ResponseWrapper(localName = "GetOnekyRepair_InstructInfoResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairInstructInfoResponse")
	public String getOnekyRepairInstructInfo(
			@WebParam(name = "strInstructInfo", targetNamespace = "http://tempuri.org/") String strInstructInfo);

	/**
	 * 
	 * @param strSMSInfo
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_SMSInfo", action = "http://tempuri.org/GetOnekyRepair_SMSInfo")
	@WebResult(name = "GetOnekyRepair_SMSInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_SMSInfo", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairSMSInfo")
	@ResponseWrapper(localName = "GetOnekyRepair_SMSInfoResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairSMSInfoResponse")
	public String getOnekyRepairSMSInfo(
			@WebParam(name = "strSMSInfo", targetNamespace = "http://tempuri.org/") String strSMSInfo);

	/**
	 * 
	 * @param strID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_SelectInstructionIssued", action = "http://tempuri.org/GetOnekyRepair_SelectInstructionIssued")
	@WebResult(name = "GetOnekyRepair_SelectInstructionIssuedResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_SelectInstructionIssued", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairSelectInstructionIssued")
	@ResponseWrapper(localName = "GetOnekyRepair_SelectInstructionIssuedResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairSelectInstructionIssuedResponse")
	public String getOnekyRepairSelectInstructionIssued(
			@WebParam(name = "strID", targetNamespace = "http://tempuri.org/") String strID);

	/**
	 * 
	 * @param strID
	 * @return returns byte[]
	 */
	@WebMethod(operationName = "GetOnekyRepair_GetLog", action = "http://tempuri.org/GetOnekyRepair_GetLog")
	@WebResult(name = "GetOnekyRepair_GetLogResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_GetLog", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairGetLog")
	@ResponseWrapper(localName = "GetOnekyRepair_GetLogResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairGetLogResponse")
	public byte[] getOnekyRepairGetLog(
			@WebParam(name = "strID", targetNamespace = "http://tempuri.org/") String strID);

	/**
	 * 
	 * @param strID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_GetQueryCmd", action = "http://tempuri.org/GetOnekyRepair_GetQueryCmd")
	@WebResult(name = "GetOnekyRepair_GetQueryCmdResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_GetQueryCmd", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairGetQueryCmd")
	@ResponseWrapper(localName = "GetOnekyRepair_GetQueryCmdResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairGetQueryCmdResponse")
	public String getOnekyRepairGetQueryCmd(
			@WebParam(name = "strID", targetNamespace = "http://tempuri.org/") String strID);

	/**
	 * 
	 * @param strId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_Ne_ByQueryCmdId", action = "http://tempuri.org/GetOnekyRepair_Ne_ByQueryCmdId")
	@WebResult(name = "GetOnekyRepair_Ne_ByQueryCmdIdResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_Ne_ByQueryCmdId", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairNeByQueryCmdId")
	@ResponseWrapper(localName = "GetOnekyRepair_Ne_ByQueryCmdIdResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairNeByQueryCmdIdResponse")
	public String getOnekyRepairNeByQueryCmdId(
			@WebParam(name = "strId", targetNamespace = "http://tempuri.org/") String strId);

	/**
	 * 
	 * @param strId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_Ne_ByCity", action = "http://tempuri.org/GetOnekyRepair_Ne_ByCity")
	@WebResult(name = "GetOnekyRepair_Ne_ByCityResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_Ne_ByCity", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairNeByCity")
	@ResponseWrapper(localName = "GetOnekyRepair_Ne_ByCityResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairNeByCityResponse")
	public String getOnekyRepairNeByCity(
			@WebParam(name = "strId", targetNamespace = "http://tempuri.org/") String strId);

	/**
	 * 
	 * @param strJson
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_Ne_ByData", action = "http://tempuri.org/GetOnekyRepair_Ne_ByData")
	@WebResult(name = "GetOnekyRepair_Ne_ByDataResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_Ne_ByData", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairNeByData")
	@ResponseWrapper(localName = "GetOnekyRepair_Ne_ByDataResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairNeByDataResponse")
	public String getOnekyRepairNeByData(
			@WebParam(name = "strJson", targetNamespace = "http://tempuri.org/") String strJson);

	/**
	 * 
	 * @param strJson
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_List_ByHCHL", action = "http://tempuri.org/GetOnekyRepair_List_ByHCHL")
	@WebResult(name = "GetOnekyRepair_List_ByHCHLResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_List_ByHCHL", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairListByHCHL")
	@ResponseWrapper(localName = "GetOnekyRepair_List_ByHCHLResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairListByHCHLResponse")
	public String getOnekyRepairListByHCHL(
			@WebParam(name = "strJson", targetNamespace = "http://tempuri.org/") String strJson);

	/**
	 * 
	 * @param strInstructionInfo
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetOnekyRepair_InstructionIssued", action = "http://tempuri.org/GetOnekyRepair_InstructionIssued")
	@WebResult(name = "GetOnekyRepair_InstructionIssuedResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetOnekyRepair_InstructionIssued", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairInstructionIssued")
	@ResponseWrapper(localName = "GetOnekyRepair_InstructionIssuedResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetOnekyRepairInstructionIssuedResponse")
	public String getOnekyRepairInstructionIssued(
			@WebParam(name = "strInstructionInfo", targetNamespace = "http://tempuri.org/") String strInstructionInfo);

	/**
	 * 
	 * @param strLoginKey
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ClientRefrash", action = "http://tempuri.org/ClientRefrash")
	@WebResult(name = "ClientRefrashResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "ClientRefrash", targetNamespace = "http://tempuri.org/", className = "wsclient.ClientRefrash")
	@ResponseWrapper(localName = "ClientRefrashResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.ClientRefrashResponse")
	public String clientRefrash(
			@WebParam(name = "strLoginKey", targetNamespace = "http://tempuri.org/") String strLoginKey);

	/**
	 * 
	 * @param strLoginKey
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ClientLogout", action = "http://tempuri.org/ClientLogout")
	@WebResult(name = "ClientLogoutResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "ClientLogout", targetNamespace = "http://tempuri.org/", className = "wsclient.ClientLogout")
	@ResponseWrapper(localName = "ClientLogoutResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.ClientLogoutResponse")
	public String clientLogout(
			@WebParam(name = "strLoginKey", targetNamespace = "http://tempuri.org/") String strLoginKey);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetUpdateInfo", action = "http://tempuri.org/GetUpdateInfo")
	@WebResult(name = "GetUpdateInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetUpdateInfo", targetNamespace = "http://tempuri.org/", className = "wsclient.GetUpdateInfo")
	@ResponseWrapper(localName = "GetUpdateInfoResponse", targetNamespace = "http://tempuri.org/", className = "wsclient.GetUpdateInfoResponse")
	public String getUpdateInfo();

}
