package wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * Onekey_App_Service service = new Onekey_App_Service();
 * OnekeyAppServiceSoap portType = service.getOnekeyAppServiceSoap();
 * portType.getOnekyRepairUserInfo(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "Onekey_App_Service", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://120.202.255.80/Onekey_App_Service.asmx?wsdl")
public class OnekeyAppService extends Service {

	private final static URL ONEKEYAPPSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(wsclient.OnekeyAppService.class
			.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = wsclient.OnekeyAppService.class.getResource(".");
			url = new URL(baseUrl, "http://120.202.255.80/Onekey_App_Service.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://120.202.255.80/Onekey_App_Service.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ONEKEYAPPSERVICE_WSDL_LOCATION = url;
	}

	public OnekeyAppService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public OnekeyAppService() {
		super(ONEKEYAPPSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/",
				"Onekey_App_Service"));
	}

	/**
	 * 
	 * @return returns OnekeyAppServiceSoap
	 */
	@WebEndpoint(name = "Onekey_App_ServiceSoap")
	public OnekeyAppServiceSoap getOnekeyAppServiceSoap() {
		return super.getPort(new QName("http://tempuri.org/", "Onekey_App_ServiceSoap"),
				OnekeyAppServiceSoap.class);
	}

	/**
	 * 
	 * @return returns OnekeyAppServiceSoap
	 */
	@WebEndpoint(name = "Onekey_App_ServiceSoap12")
	public OnekeyAppServiceSoap getOnekeyAppServiceSoap12() {
		return super.getPort(new QName("http://tempuri.org/", "Onekey_App_ServiceSoap12"),
				OnekeyAppServiceSoap.class);
	}

	/**
	 * 
	 * @return returns OnekeyAppServiceHttpGet
	 */
	@WebEndpoint(name = "Onekey_App_ServiceHttpGet")
	public OnekeyAppServiceHttpGet getOnekeyAppServiceHttpGet() {
		return super.getPort(new QName("http://tempuri.org/", "Onekey_App_ServiceHttpGet"),
				OnekeyAppServiceHttpGet.class);
	}

	/**
	 * 
	 * @return returns OnekeyAppServiceHttpPost
	 */
	@WebEndpoint(name = "Onekey_App_ServiceHttpPost")
	public OnekeyAppServiceHttpPost getOnekeyAppServiceHttpPost() {
		return super.getPort(new QName("http://tempuri.org/", "Onekey_App_ServiceHttpPost"),
				OnekeyAppServiceHttpPost.class);
	}

}
